import { describe, expect, test } from "bun:test";
import { chmod, mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import {
  findExecutableOnPath,
  installPreflightWrappers,
  isPreflightWrapper,
  parsePreflightWrappedCommand,
  renderPreflightWrapper,
  VPNCTL_PREFLIGHT_WRAPPER_MARKER,
} from "../src/core/preflight-wrapper";

describe("renderPreflightWrapper", () => {
  test("contains the vpnctl-wrap marker", () => {
    const result = renderPreflightWrapper("claude", "/usr/local/bin/claude");
    expect(result).toContain(VPNCTL_PREFLIGHT_WRAPPER_MARKER);
  });

  test("hardcodes the resolved absolute path, not the bare command name", () => {
    const result = renderPreflightWrapper("claude", "/usr/local/bin/claude");
    expect(result).toContain("exec vpnctl exec -- /usr/local/bin/claude");
    expect(result).not.toMatch(/exec vpnctl exec -- claude(?!\s*\/)/);
  });

  test("passes through all arguments with $@", () => {
    const result = renderPreflightWrapper("codex", "/opt/homebrew/bin/codex");
    expect(result).toContain('"$@"');
  });

  test("produces an executable sh shebang", () => {
    const result = renderPreflightWrapper("claude", "/usr/local/bin/claude");
    expect(result).toMatch(/^#!\/bin\/sh\n/);
  });
});

describe("isPreflightWrapper", () => {
  test("returns true for wrapper generated by renderPreflightWrapper", () => {
    expect(isPreflightWrapper(renderPreflightWrapper("claude", "/usr/local/bin/claude"))).toBe(true);
  });

  test("returns false for an arbitrary shell script without the marker", () => {
    expect(isPreflightWrapper('#!/bin/sh\nexec claude "$@"\n')).toBe(false);
  });

  test("returns false for empty string", () => {
    expect(isPreflightWrapper("")).toBe(false);
  });
});

describe("parsePreflightWrappedCommand", () => {
  test("extracts the resolved path from a wrapper", () => {
    const wrapper = renderPreflightWrapper("claude", "/usr/local/bin/claude");
    expect(parsePreflightWrappedCommand(wrapper)).toBe("/usr/local/bin/claude");
  });

  test("returns null for content without an exec line", () => {
    expect(parsePreflightWrappedCommand("#!/bin/sh\necho hello\n")).toBeNull();
  });
});

describe("findExecutableOnPath", () => {
  test("skips the wrapper directory to avoid recursive wrappers", async () => {
    const dir = await mkdtemp(path.join(os.tmpdir(), "vpnctl-preflight-wrapper-test-"));
    const wrapperDir = path.join(dir, "wrappers");
    const commandDir = path.join(dir, "commands");

    try {
      await mkdir(wrapperDir);
      await mkdir(commandDir);
      await writeFile(path.join(wrapperDir, "codex"), "#!/bin/sh\nexit 1\n");
      await writeFile(path.join(commandDir, "codex"), "#!/bin/sh\nexit 0\n");
      await chmod(path.join(wrapperDir, "codex"), 0o755);
      await chmod(path.join(commandDir, "codex"), 0o755);

      expect(await findExecutableOnPath("codex", `${wrapperDir}:${commandDir}`, wrapperDir)).toBe(path.join(commandDir, "codex"));
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });
});

describe("installPreflightWrappers", () => {
  test("installs selected wrappers to the wrapper directory", async () => {
    const dir = await mkdtemp(path.join(os.tmpdir(), "vpnctl-preflight-install-test-"));
    const wrapperDir = path.join(dir, "wrappers");
    const commandDir = path.join(dir, "commands");

    try {
      await mkdir(commandDir, { recursive: true });
      await writeFile(path.join(commandDir, "claude"), "#!/bin/sh\nexit 0\n");
      await chmod(path.join(commandDir, "claude"), 0o755);

      const results = await installPreflightWrappers(["claude"], { dir: wrapperDir, pathValue: commandDir });

      expect(results).toHaveLength(1);
      expect(results[0]?.status).toBe("installed");
      const wrapper = await Bun.file(path.join(wrapperDir, "claude")).text();
      expect(wrapper).toContain(`exec vpnctl exec -- ${path.join(commandDir, "claude")}`);
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });
});
