import { describe, expect, test } from "bun:test";
import { isVpnctlWrapper, parseWrappedCommand, renderWrapper, VPNCTL_WRAP_MARKER } from "../src/cli/commands/wrap";

describe("renderWrapper", () => {
  test("contains the vpnctl-wrap marker", () => {
    const result = renderWrapper("claude", "/usr/local/bin/claude");
    expect(result).toContain(VPNCTL_WRAP_MARKER);
  });

  test("hardcodes the resolved absolute path, not the bare command name", () => {
    const result = renderWrapper("claude", "/usr/local/bin/claude");
    expect(result).toContain("exec vpnctl exec -- /usr/local/bin/claude");
    expect(result).not.toMatch(/exec vpnctl exec -- claude(?!\s*\/)/);
  });

  test("passes through all arguments with $@", () => {
    const result = renderWrapper("codex", "/opt/homebrew/bin/codex");
    expect(result).toContain('"$@"');
  });

  test("produces an executable sh shebang", () => {
    const result = renderWrapper("claude", "/usr/local/bin/claude");
    expect(result).toMatch(/^#!\/bin\/sh\n/);
  });
});

describe("isVpnctlWrapper", () => {
  test("returns true for wrapper generated by renderWrapper", () => {
    expect(isVpnctlWrapper(renderWrapper("claude", "/usr/local/bin/claude"))).toBe(true);
  });

  test("returns false for an arbitrary shell script without the marker", () => {
    expect(isVpnctlWrapper('#!/bin/sh\nexec claude "$@"\n')).toBe(false);
  });

  test("returns false for empty string", () => {
    expect(isVpnctlWrapper("")).toBe(false);
  });
});

describe("parseWrappedCommand", () => {
  test("extracts the resolved path from a wrapper", () => {
    const wrapper = renderWrapper("claude", "/usr/local/bin/claude");
    expect(parseWrappedCommand(wrapper)).toBe("/usr/local/bin/claude");
  });

  test("returns null for content without an exec line", () => {
    expect(parseWrappedCommand("#!/bin/sh\necho hello\n")).toBeNull();
  });
});
