import { chmodSync, statSync, watch } from "node:fs";
import path from "node:path";
import SysTrayDefault from "systray2";
import { isCompiledBinary } from "../core/runtime";
import { writeDesiredTunnel } from "../core/desired-tunnel";
import { LOG_DIR, STATE_FILE } from "../core/paths";
import { classifyState, parseStateFile, type TrayStatus } from "../core/state-file";

// `bun build --compile` double-wraps systray2's CJS default export: the real
// constructor sits at `.default.default` in the shipped binary but at `.default`
// under `bun run`. The runtime shape doesn't match the published types, so this
// boundary is genuinely untyped — pick whichever level is the constructor, else
// `new SysTray(...)` throws "Object is not a constructor" in the release build.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function unwrapSysTrayConstructor(imported: any): typeof SysTrayDefault {
  // eslint-disable-next-line @typescript-eslint/no-unsafe-return, @typescript-eslint/no-unsafe-member-access
  return typeof imported === "function" ? imported : imported.default;
}
const SysTray = unwrapSysTrayConstructor(SysTrayDefault);

// fs.watch is the fast path, but it's unreliable on macOS (FSEvents coalescing),
// so poll often enough that a state change still reflects within ~1s even when the
// watch lags, and to catch the tunnel-down ⇒ stale ⇒ "unknown" transition (which
// produces no file write to watch for).
const FALLBACK_POLL_INTERVAL_MS = 1_000;
const TRAY_BINARY_NAME = "tray_darwin_release";
const TRAY_BINARY_MODE = 0o755;
const OPEN_LOGS_ITEM_TITLE = "Open logs";
const TURN_TUNNEL_ON_TITLE = "Turn tunnel on";
const TURN_TUNNEL_OFF_TITLE = "Turn tunnel off";

// systray2 assigns each menu item a 1-based __id (depth-first); the toggle is the
// first item. update-item targets this id to refresh the toggle's title in place.
const TUNNEL_TOGGLE_ITEM_ID = 1;

// 36×36 RGBA non-template shields generated by scripts/gen-tray-icons.ts: green
// shield + checkmark (protected), red shield + alert (fail-closed), gray outline
// (unknown). Non-template because the helper can't toggle that flag per update.
const ICON_PROTECTED =
  "iVBORw0KGgoAAAANSUhEUgAAACQAAAAkCAYAAADhAJiYAAABMklEQVR4nO3X0Q2DIBAGYEZwBB95dISO0A1wBEfoBo7gCDeCIziCIzgCDQkkxnLAHSg28eF/asJ9lbuzFRKUuFOqA/4S1EpQIEHpkwO2VhQ0X4BxmVNA+uI8oOcJPT2U8wQ2CWqUoKY7TJnBdLtzp5qgI8akrwXyYRoJaqkFennOxDCng3rPeaGGzgJNkcfPwWSBmkBPcDFJIOy+30ij5mCWFBAQpkdkYLStFQV9iCPNxWhbKwrqIodgqIExlT/nYN90JaKwLRzK6quNgcZCL85QRgqoZRahpKWAOA1KiVuyJFBjr6U0Zjss2WSQsMuwNOi4YEmg1AbPamQqqFQ/oX3DAXEXn8uQWocCEnYZUv77z4nvPzbI5WWvwDeFm/3M98vxNJDYxYywKW6CjvOVoKL5Ao8Q0MSNx33vAAAAAElFTkSuQmCC";
const ICON_FAIL_CLOSED =
  "iVBORw0KGgoAAAANSUhEUgAAACQAAAAkCAYAAADhAJiYAAABDUlEQVR4nO2XwQmEMBBFU4IlpARvuW4JlmAJlpAOLMESUkJKsASxAktwCczCHFZ2/myMCjl8CMifPMOfOJrVOXMnXQ7wSCC7OhdW5/aTFWivn0CxAMxHUQK0F1YFqid0uwzN1L6W1pcDvZg3rStQPaGaodpl/95Dc8F7aJYAocNZz7w96A0SIA8W3cjjaY14vQSoBYtOzDuB3lY65C9AUT4XW8C3SIf8pBEo3DFfB/hGBAh505SbgYRkyCJAmjxocycGahRdIz3RRgOEZkKTORgIDbgqyChQrjwd5kYDZKiLtDCDdB8EyNDNivz7x2+3cU4g/lWfDrpwo2d8CjgdyDClFk6bJx22c0mgrHoDjL5qcOtHdSwAAAAASUVORK5CYII=";
const ICON_UNKNOWN =
  "iVBORw0KGgoAAAANSUhEUgAAACQAAAAkCAYAAADhAJiYAAABM0lEQVR4nO2X0Q2EIAyGHcERHMERHMERHMER2MC3vjKCIziCIzgCI9zFBJOmorQevTsTHv7EBykf9C+UCgCqf9LPAR4J1ADADAAvZc1hriTQ8gWYXQsHiA5yYWAOuUh8EdCg4JPhLtCqaN71DtAhvxmFfVqAyg4VD5UqK+fQ4w/G/Z5xikDu7L6M/Yybs1oBpiZNWhLIoAG9AlCP4hsOUIsGWAUgi+K3HCCcY68A5K88ejZoUuoacbc4SYAa0lPnMHdNeupGAkRzfTDfDRmON1Mr8pkqDleWv9pxaaBDVTDUShbGCYgN7oUmHwhM1MhSIOqn/Z7rLv7vIi9g1pkm2frx5FVrg2FN+I69TkfuPHf8IHn7L1LfSYFwSizxB/aZTaQ0O1CFtJXwNvmmjw/QHEBZ9QYIMuhcgFrzXwAAAABJRU5ErkJggg==";

const ICONS: Record<TrayStatus, string> = {
  protected: ICON_PROTECTED,
  "fail-closed": ICON_FAIL_CLOSED,
  unknown: ICON_UNKNOWN,
};

function statusLabel(status: TrayStatus): string {
  if (status === "protected") return "Protected — tunnel up";
  if (status === "fail-closed") return "Fail-closed — tunnel down, traffic blocked";
  return "Unknown — daemon not running or state stale";
}

function toggleTitle(status: TrayStatus): string {
  return status === "protected" ? TURN_TUNNEL_OFF_TITLE : TURN_TUNNEL_ON_TITLE;
}

function tunnelToggleItem(status: TrayStatus) {
  return { __id: TUNNEL_TOGGLE_ITEM_ID, title: toggleTitle(status), tooltip: `vpnctl: ${statusLabel(status)}`, enabled: true };
}

function buildMenu(status: TrayStatus) {
  return {
    icon: ICONS[status],
    title: "",
    tooltip: `vpnctl: ${statusLabel(status)}`,
    items: [
      tunnelToggleItem(status),
      SysTray.separator,
      { title: OPEN_LOGS_ITEM_TITLE, tooltip: "Open the vpnctl log folder", enabled: true },
    ],
  };
}

// systray2 spawns a precompiled Go binary it locates at `./traybin/<name>`
// (cwd) or `<module dir>/traybin/<name>`. A `bun build --compile` binary has no
// real module dir, so we ship the Go binary in `traybin/` next to the compiled
// vpnctl-tray and chdir there. We also chmod +x: `bun install` drops the
// executable bit during extraction (a tar-based release preserves it, but the
// chmod is idempotent and harmless either way).
function prepareTrayBinary(): void {
  const baseDir = isCompiledBinary() ? path.dirname(process.execPath) : path.resolve(import.meta.dir, "../../node_modules/systray2");
  ensureExecutable(path.join(baseDir, "traybin", TRAY_BINARY_NAME));
  if (isCompiledBinary()) process.chdir(baseDir);
}

function ensureExecutable(binaryPath: string): void {
  try {
    if ((statSync(binaryPath).mode & 0o111) !== 0) return;
    chmodSync(binaryPath, TRAY_BINARY_MODE);
  } catch {
    // Best-effort: a root-owned install dir denies chmod to the per-user agent,
    // but that's fine as long as the binary already carries +x (a tar-based
    // release preserves it). systray2 surfaces a real spawn error if it doesn't.
  }
}

function openLogs(): void {
  Bun.spawn(["/usr/bin/open", LOG_DIR]);
}

async function readStatus(): Promise<TrayStatus> {
  const text = await Bun.file(STATE_FILE)
    .text()
    .catch(() => null);
  return classifyState(text === null ? null : parseStateFile(text), Date.now());
}

async function main(): Promise<void> {
  prepareTrayBinary();

  let currentStatus = await readStatus();
  const systray = new SysTray({ menu: buildMenu(currentStatus), debug: false, copyDir: false });
  await systray.ready();

  await systray.onClick((action) => {
    // Only "Open logs" has a stable title; the toggle's title changes with state
    // and its click payload can be stale, so match the static item and treat any
    // other click as the toggle — driven by tracked status, not the clicked label.
    if (action.item.title === OPEN_LOGS_ITEM_TITLE) openLogs();
    else void writeDesiredTunnel(currentStatus === "protected" ? "down" : "up");
  });

  const applyStatus = async (): Promise<void> => {
    const next = await readStatus();
    if (next !== currentStatus) {
      currentStatus = next;
      // Two separate actions: systray2's combined "update-menu-and-item" doesn't
      // match the Go binary's "update-item-and-menu" handler and gets dropped (it
      // also wedges click handling). update-menu swaps the icon; update-item
      // refreshes the toggle title in place.
      await systray.sendAction({ type: "update-menu", menu: buildMenu(currentStatus) });
      await systray.sendAction({ type: "update-item", item: tunnelToggleItem(currentStatus) });
    }
  };

  // Watch the state file's directory so an `up`/`down` write (or a monitor tick)
  // updates the icon immediately; filter to the state file by name. Watching the
  // directory survives the file being atomically replaced (a new inode).
  const stateFileName = path.basename(STATE_FILE);
  const watcher = watch(path.dirname(STATE_FILE), (_event, filename) => {
    if (filename === stateFileName) void applyStatus();
  });

  try {
    while (!systray.killed) {
      await Bun.sleep(FALLBACK_POLL_INTERVAL_MS);
      await applyStatus();
    }
  } finally {
    watcher.close();
  }
}

if (import.meta.main) {
  await main();
}
