import { chmodSync, statSync } from "node:fs";
import path from "node:path";
import SysTray from "systray2";
import { isCompiledBinary } from "../core/runtime";
import { LAUNCHD_LABEL_TRAY, STATE_FILE } from "../core/paths";
import { classifyState, parseStateFile, type TrayStatus } from "../core/state-file";

const POLL_INTERVAL_MS = 3_000;
const TRAY_BINARY_NAME = "tray_darwin_release";
const TRAY_BINARY_MODE = 0o755;
const QUIT_ITEM_TITLE = "Quit vpnctl tray";

// 16×16 RGBA circles generated by scripts/gen-tray-icons.ts.
const ICON_PROTECTED =
  "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAdElEQVR4nGPQOBHAgAOra5wI8IBidVzqsAlmaZwIuKpxIuA/Gr4KlcNpAJvGiYCNWDSi441QtRgGEKMZ2RAUA7JI0AzDWcgGYPMzIXwVZoA6GZphWJ0BGk3kGuBBFQMo9gLFgUiVaGSgNCFRJSlTnJnIys4A6AvmjBCZF4kAAAAASUVORK5CYII=";
const ICON_FAIL_CLOSED =
  "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAcklEQVR4nK2TsRHAIAhFqbIK/Z/CWdzOYejYJWnwzhi9JEDxGuW/OwVIAdrAChSDd3Wrw6qAKHBOiN1tBYcCbRGcaVb7EHwJj5KboP4Id+ooWL35DekCdoQ7TNYmr6CkCMJPCH9iShspOkgpoxxeJtc6X7oa5ow9FGklAAAAAElFTkSuQmCC";
const ICON_UNKNOWN =
  "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAcElEQVR4nK2TwQ3AIAhFOXUVVnEWB3p7OIzztBdMrMW0FQ/vovyXKCCATFAgGTqr8w4zUIFzoNrdVHAAxQmOFKt9CL6Ee8lNkH+EG7kXeG9+ozaBLoQbKtamVUHaIgg/IfyJW9oo0UHaMsrhZVpa5wtwkmibExJKagAAAABJRU5ErkJggg==";

const ICONS: Record<TrayStatus, string> = {
  protected: ICON_PROTECTED,
  "fail-closed": ICON_FAIL_CLOSED,
  unknown: ICON_UNKNOWN,
};

function statusLabel(status: TrayStatus): string {
  if (status === "protected") return "Protected — tunnel up";
  if (status === "fail-closed") return "Fail-closed — tunnel down, traffic blocked";
  return "Unknown — daemon not running or state stale";
}

function buildMenu(status: TrayStatus) {
  return {
    icon: ICONS[status],
    title: "",
    tooltip: `vpnctl: ${statusLabel(status)}`,
    items: [
      { title: statusLabel(status), tooltip: "", enabled: false },
      SysTray.separator,
      { title: QUIT_ITEM_TITLE, tooltip: "Stop showing the vpnctl tray icon", enabled: true },
    ],
  };
}

// systray2 spawns a precompiled Go binary it locates at `./traybin/<name>`
// (cwd) or `<module dir>/traybin/<name>`. A `bun build --compile` binary has no
// real module dir, so we ship the Go binary in `traybin/` next to the compiled
// vpnctl-tray and chdir there. We also chmod +x: `bun install` drops the
// executable bit during extraction (a tar-based release preserves it, but the
// chmod is idempotent and harmless either way).
function prepareTrayBinary(): void {
  const baseDir = isCompiledBinary() ? path.dirname(process.execPath) : path.resolve(import.meta.dir, "../../node_modules/systray2");
  ensureExecutable(path.join(baseDir, "traybin", TRAY_BINARY_NAME));
  if (isCompiledBinary()) process.chdir(baseDir);
}

function ensureExecutable(binaryPath: string): void {
  try {
    if ((statSync(binaryPath).mode & 0o111) !== 0) return;
    chmodSync(binaryPath, TRAY_BINARY_MODE);
  } catch {
    // Best-effort: a root-owned install dir denies chmod to the per-user agent,
    // but that's fine as long as the binary already carries +x (a tar-based
    // release preserves it). systray2 surfaces a real spawn error if it doesn't.
  }
}

// The "Quit" menu item should actually stop the tray. With KeepAlive the agent
// would just relaunch on a plain exit, so boot it out of the GUI domain first;
// it returns at next login (RunAtLoad). In a dev run (no launchd job) the
// bootout is a harmless no-op and kill() still exits.
function quit(systray: SysTray): void {
  const uid = String(process.getuid?.() ?? 0);
  Bun.spawnSync(["/bin/launchctl", "bootout", `gui/${uid}/${LAUNCHD_LABEL_TRAY}`]);
  void systray.kill();
}

async function readStatus(): Promise<TrayStatus> {
  const text = await Bun.file(STATE_FILE)
    .text()
    .catch(() => null);
  return classifyState(text === null ? null : parseStateFile(text), Date.now());
}

async function main(): Promise<void> {
  prepareTrayBinary();

  let currentStatus = await readStatus();
  const systray = new SysTray({ menu: buildMenu(currentStatus), debug: false, copyDir: false });
  await systray.ready();

  await systray.onClick((action) => {
    if (action.item.title === QUIT_ITEM_TITLE) quit(systray);
  });

  while (!systray.killed) {
    await Bun.sleep(POLL_INTERVAL_MS);
    const next = await readStatus();
    if (next !== currentStatus) {
      currentStatus = next;
      await systray.sendAction({ type: "update-menu", menu: buildMenu(currentStatus) });
    }
  }
}

if (import.meta.main) {
  await main();
}
